import { supabase, demoData, getTable, getSettings } from './supabase.js';
const $=s=>document.querySelector(s); let current='settings';
async function boot(){ const {data}=await supabase.auth.getSession(); if(data.session) showAdmin(); else showLogin(); }
function showLogin(){ $('#loginPanel').classList.remove('hidden'); $('#adminPanel').classList.add('hidden'); }
function showAdmin(){ $('#loginPanel').classList.add('hidden'); $('#adminPanel').classList.remove('hidden'); renderTab(current); }
$('#loginBtn').onclick=async()=>{ $('#loginMsg').textContent='Entrando...'; const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value}); if(error){$('#loginMsg').textContent='Erro: '+error.message; return} showAdmin(); };
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut(); showLogin();};
document.querySelector('.admin-menu').onclick=e=>{ if(e.target.tagName!=='BUTTON')return; document.querySelectorAll('.admin-menu button').forEach(b=>b.classList.remove('active')); e.target.classList.add('active'); current=e.target.dataset.tab; renderTab(current); };
function input(name,label,value='',type='text'){return `<div class="field"><label>${label}</label><input id="${name}" type="${type}" value="${value??''}"></div>`}
function textarea(name,label,value=''){return `<div class="field"><label>${label}</label><textarea id="${name}" rows="4">${value??''}</textarea></div>`}
async function renderTab(tab){ if(tab==='settings') return settingsForm(); if(tab==='projects') return crudProjects(); if(tab==='services') return simpleCrud('services',demoData.services,['title','description','icon']); if(tab==='skills') return simpleCrud('skills',demoData.skills,['name','level']); if(tab==='tech') return simpleCrud('technologies',demoData.technologies.map(name=>({name})),['name']); if(tab==='stats') return simpleCrud('statistics',demoData.stats,['value','label']); if(tab==='testimonials') return simpleCrud('testimonials',demoData.testimonials,['client','role','text']); }
async function settingsForm(){ const s=await getSettings(); $('#adminContent').innerHTML=`<h2>Configurações do site</h2><div class="form-grid">${input('site_title','Título do site',s.site_title)}${input('email','Email',s.email)}${input('whatsapp_url','WhatsApp',s.whatsapp_url)}${input('resume_url','Currículo PDF',s.resume_url)}${input('github_url','GitHub',s.github_url)}${input('linkedin_url','LinkedIn',s.linkedin_url)}${input('instagram_url','Instagram',s.instagram_url)}${input('favicon_url','Favicon',s.favicon_url||'')}</div>${textarea('hero_description','Descrição do Hero',s.hero_description)}${textarea('about_text','Texto Sobre',s.about_text)}<button class="btn pink" id="saveSettings">Salvar configurações</button><p id="saveMsg"></p>`; $('#saveSettings').onclick=async()=>{ const payload={id:1,site_title:$('#site_title').value,email:$('#email').value,whatsapp_url:$('#whatsapp_url').value,resume_url:$('#resume_url').value,github_url:$('#github_url').value,linkedin_url:$('#linkedin_url').value,instagram_url:$('#instagram_url').value,favicon_url:$('#favicon_url').value,hero_description:$('#hero_description').value,about_text:$('#about_text').value}; const {error}=await supabase.from('site_settings').upsert(payload); $('#saveMsg').textContent=error?'Erro: '+error.message:'Salvo com sucesso.'; }; }
async function crudProjects(){ const items=await getTable('projects',demoData.projects); $('#adminContent').innerHTML=`<h2>Projetos</h2><div class="form-grid">${input('p_title','Título')}${input('p_slug','Slug')}${input('p_category','Categoria')}${input('p_cover','URL da capa')}${input('p_url','Link do projeto')}${input('p_order','Ordem','0','number')}</div>${textarea('p_description','Descrição')}${textarea('p_problem','Problema')}${textarea('p_solution','Solução')}${textarea('p_results','Resultados')}<div class="field"><label>Tecnologias separadas por vírgula</label><input id="p_tech" placeholder="HTML, CSS, Supabase"></div><label><input id="p_featured" type="checkbox"> Projeto em destaque</label><br><br><button class="btn pink" id="addProject">Adicionar / salvar projeto</button><div id="list"></div>`; $('#list').innerHTML=items.map(i=>`<div class="table-item"><span><b>${i.title}</b><br><small>${i.category||''}</small></span><span><button data-edit='${JSON.stringify(i).replaceAll("'","&apos;")}' class="btn light edit">Editar</button><button data-id="${i.id}" class="btn dark del">Excluir</button></span></div>`).join(''); $('#addProject').onclick=async()=>{ const payload={title:$('#p_title').value,slug:$('#p_slug').value,category:$('#p_category').value,cover:$('#p_cover').value,project_url:$('#p_url').value,order_index:Number($('#p_order').value||0),description:$('#p_description').value,problem:$('#p_problem').value,solution:$('#p_solution').value,results:$('#p_results').value,technologies:$('#p_tech').value.split(',').map(x=>x.trim()).filter(Boolean),featured:$('#p_featured').checked}; const {error}=await supabase.from('projects').upsert(payload,{onConflict:'slug'}); alert(error?error.message:'Projeto salvo'); crudProjects();}; $('#list').onclick=async e=>{ if(e.target.classList.contains('del')){ if(confirm('Excluir projeto?')){await supabase.from('projects').delete().eq('id',e.target.dataset.id); crudProjects();} } if(e.target.classList.contains('edit')){ const p=JSON.parse(e.target.dataset.edit.replaceAll('&apos;',"'")); $('#p_title').value=p.title||''; $('#p_slug').value=p.slug||''; $('#p_category').value=p.category||''; $('#p_cover').value=p.cover||''; $('#p_url').value=p.project_url||''; $('#p_order').value=p.order_index||0; $('#p_description').value=p.description||''; $('#p_problem').value=p.problem||''; $('#p_solution').value=p.solution||''; $('#p_results').value=p.results||''; $('#p_tech').value=(p.technologies||[]).join(', '); $('#p_featured').checked=!!p.featured; scrollTo(0,0);} }; }
async function simpleCrud(table,fallback,fields){ const items=await getTable(table,fallback); $('#adminContent').innerHTML=`<h2>${table}</h2><div class="form-grid">${fields.map(f=>input('f_'+f,f)).join('')}</div><button class="btn pink" id="addSimple">Adicionar</button><div id="simpleList"></div>`; $('#simpleList').innerHTML=items.map(i=>`<div class="table-item"><span>${fields.map(f=>`<b>${f}:</b> ${i[f]??''}`).join(' • ')}</span><button class="btn dark" data-id="${i.id}">Excluir</button></div>`).join(''); $('#addSimple').onclick=async()=>{let payload={};fields.forEach(f=>payload[f]=$('#f_'+f).value); if(payload.level)payload.level=Number(payload.level); const {error}=await supabase.from(table).insert(payload); alert(error?error.message:'Salvo'); simpleCrud(table,fallback,fields);}; $('#simpleList').onclick=async e=>{if(e.target.dataset.id){await supabase.from(table).delete().eq('id',e.target.dataset.id); simpleCrud(table,fallback,fields);}}; }
boot();
